In [19]:
import scipy.stats as stats
import statsmodels.api as sm
from scipy.stats import chi2_contingency
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
from PIL import ImageGrab
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
buyer=pd.read_csv('C:\\Users\\aamir\\Documents\\DATA SCIENCE\\.spyder-py3\\working practice\\BuyerRatio.csv')
buyer

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [21]:
buyer.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [22]:
# Create a list of the observed values for males and females in each region
observed_values = np.array([[50, 142, 131, 70], [435, 1523, 1356, 750]])

# Use the chi2_contingency function to calculate the test statistic and p-value
chi2_statistic, p_value, dof, expected_values = chi2_contingency(observed_values)


In [26]:
table = [[50,142,131,70],
        [435,1523,1356,750]]


In [27]:
stat, p, dof, exp = stats.chi2_contingency(table) 
print(stat,"\n", p,"\n", dof,"\n", exp)


1.595945538661058 
 0.6603094907091882 
 3 
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [28]:
stats.chi2_contingency(table) 

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [29]:
observed = np.array([50, 142, 131, 70, 435, 1523, 1356, 750])
expected = np.array([42.76531299,  146.81287862,  131.11756787, 72.30424052, 442.23468701, 1518.18712138, 1355.88243213, 747.69575948])

In [30]:
statistics, p_value = stats.chisquare(observed, expected, ddof = 3)
print("Statistics = ",statistics,"\n",'P_Value = ', p_value)

Statistics =  1.5959455390914483 
 P_Value =  0.8095206646905712


In [31]:
alpha = 0.05
print('Significnace=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
    print('We reject Null Hypothesis there is a significance difference between TAT of reports of the laboratories')
else:
    print('We fail to reject Null hypothesis')

Significnace=0.050, p=0.810
We fail to reject Null hypothesis
